-- สร้างตาราง clinic_hd_claim สำหรับเก็บข้อมูลทะเบียนส่งเบิกเคลมฟอกเลือด
-- รันใน database ของ HOSxP

CREATE TABLE IF NOT EXISTS `clinic_hd_claim` (
  `clinic_hd_dmis_claim_id`   INT             NOT NULL AUTO_INCREMENT,
  `clinic_hd_service_id`      INT             DEFAULT NULL,
  `vn`                        VARCHAR(12)     DEFAULT NULL,
  `hn`                        VARCHAR(9)      DEFAULT NULL,
  `clinic_hd_onset`           DATE            DEFAULT NULL,
  `clinic_hd_onset_time`      TIME            DEFAULT NULL,
  `clinic_hd_off_time`        TIME            DEFAULT NULL,
  `clinic_hd_pre_weight`      DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_pre_bps`         INT             DEFAULT NULL,
  `clinic_hd_pre_bpd`         INT             DEFAULT NULL,
  `clinic_hd_post_weight`     DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_post_bps`        INT             DEFAULT NULL,
  `clinic_hd_post_bpd`        INT             DEFAULT NULL,
  `clinic_hd_height`          DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_creatinine`      DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_albumin`         DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_ultrafiltration` DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_urr`             DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_ktv`             DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_hb`              DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_hct`             DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_pre_dialysis_bun`  DOUBLE(15,3)  DEFAULT NULL,
  `clinic_hd_post_dialysis_bun` DOUBLE(15,3)  DEFAULT NULL,
  `clinic_hd_blood_flow`      DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_blood_flow_rate` DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_membrane`        VARCHAR(100)    DEFAULT NULL,
  `clinic_hd_dialyzer`        VARCHAR(100)    DEFAULT NULL,
  `clinic_hd_vascular_access` VARCHAR(50)     DEFAULT NULL,
  `clinic_hd_cath`            VARCHAR(100)    DEFAULT NULL,
  `clinic_hd_spec_cond`       VARCHAR(50)     DEFAULT NULL,
  `clinic_hd_new_dialyze`     CHAR(1)         DEFAULT NULL,
  `clinic_hd_mode`            VARCHAR(20)     DEFAULT NULL,
  `clinic_hd_esa_epo`         TEXT            DEFAULT NULL,
  `clinic_hd_qty`             TEXT            DEFAULT NULL,
  `clinic_hd_route`           TEXT            DEFAULT NULL,
  `clinic_hd_claim_amount`    DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_iv_iron`         DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_lowmolheparin`   DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_dbllumen`        DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_parnutr`         DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_lab_xray`        DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_humanalb`        DOUBLE(15,3)    DEFAULT NULL,
  `clinic_hd_claim_sent`      CHAR(1)         DEFAULT NULL,
  `clinic_hd_claim_sent_at`   DATETIME        DEFAULT NULL,
  `clinic_hd_claim_sent_by`   VARCHAR(15)     DEFAULT NULL,
  `lastupdate`                DATETIME        DEFAULT NULL,
  `clinic_hd_confirm_status`  VARCHAR(20)     DEFAULT NULL,
  `clinic_hd_confirm_remark`  VARCHAR(500)    DEFAULT NULL,
  PRIMARY KEY (`clinic_hd_dmis_claim_id`),
  UNIQUE KEY `uk_vn` (`vn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
